### ISSUE TITLE
/pard transformed into d after #ENDIF# statement 

### ISSUE THREAD

**Issue by seeker25** [gmddmg/NTemplates#1]
Whenever I seem to be using the IF condition 

 #IF (S.MyVarHere == true)#
Print Text Here
#ENDIF#
\pard \ltrpar\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 {\rtlch\fcs1 \af0 \ltrch\fcs0 \insrsid12073270 }{\rtlch\fcs1 

there seems to be written a d into the RTF. 
/pard apparently becomes d inside the RTF. 

S.MyVarHere = false;
Result filled template file:

d \ltrpar\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 {\rtlch\fcs1 \af0 \ltrch\fcs0 \insrsid12073270 }{\rtlch\fcs1 

Going to debug the library and figure out what's going on.

**Comment by seeker25** [comment]
Apparently \par is being replaced into \\del. 
But this doesn't check to see if it is \pard -> \\DELd
then Replace \\DELd with \\DEL -> d

**Comment by gmddmg** [comment]
Probably you are correct!! I don´t know when I would be able to fix this, though. But you can get the code and fix it locally, right?

**Comment by gmddmg** [comment]
Thks for the info. I will do my best to fix ASAP!

**Comment by seeker25** [comment]
Yeah I commented out the entire replacing. I'm not sure why you took out
\par in the first place.

**Comment by seeker25** [comment]
I'll upload a fix for this shortly.

**Comment by gmddmg** [comment]
Great. To be honest, I wish I could recall the reason for that replacement. But I´m sure there must be one. I wrote this code a long time ago and I was learning about RTF on the go.

**Comment by seeker25** [comment]
That's alright, no worries. 
I'm just learning about RTF myself.

**Comment by seeker25** [comment]
I noticed running the examples to compare.. that you were relying on:

`
        private void PreprocessText()
        {
            //Check to see if must work with RTF or plain text format.
            /*idFmt = TextFormat == eTextFormat.Text ? (IDocumentFormat)new TextFormat() : (IDocumentFormat)new RTFFormat();
            //Get Matches for any possible placeholder
            Regex regex0 = CommonMethods.GetRegex(KeywordsRegExString);
            MatchCollection matchCollInit = regex0.Matches(_RTFText.ToString());
            //Replaces every 'new line' sequence with '\DEL' sequence.
            foreach (Match m in matchCollInit)
            {
                int i = RTFInput.ToString().IndexOf(idFmt.NewLine, m.Index);
                if (i >= 0)
                {
                    RTFInput = RTFInput.Remove(i, idFmt.NewLine.Length);
                    RTFInput = RTFInput.Insert(i, "\\DEL");
                }
            }
            RTFInput = RTFInput.Replace("\\DEL", "");*/
        }
`


 this to get rid of extra paragraph blocks. 

In my template I just edited .RTF file and took out the offending par's so they wouldn't be part of the template. 

So the examples were working with this commit, but I noticed the spacing is a bit out of wack.

**Comment by seeker25** [comment]
I think the best option here is to:

Create an option to toggle preprocessing of text. We can switch this on or off. We can toggle these on for your examples, and if anyone doesn't want the preprocessing they can simply turn it off. 

Stay tuned. I've almost got the testing working, plus a fix for this.

**Comment by gmddmg** [comment]
The idea of preprocessing is to have an easy way of removing the "programming sentences" after generating the document.
This function (just in case I missinterpreted you) is always used, not only for the examples.  I just run the invoice example and noticed is not working as expected (Please see the image attached, th edetails should show up in a single block). I will rollback your changes and let you know.

![invoice](https://user-images.githubusercontent.com/5861012/32116754-5531fa4e-bb22-11e7-8093-94c638434b44.JPG)

**Comment by seeker25** [comment]
I've already created another pull request fixing this.

[image: Inline image 1]

**Comment by gmddmg** [comment]
This is actually the way it´s supposed to look so I guess that commenting that part out won´t work, I will have to rollback your changes I´m afraid.

![invoice - fixed](https://user-images.githubusercontent.com/5861012/32116904-c68b065e-bb22-11e7-9cd2-f1fe71d8de5d.JPG)

**Comment by seeker25** [comment]
Try my new merge request, it will work + please try the tests.

**Comment by gmddmg** [comment]
Ok! Let me take a look!

**Comment by seeker25** [comment]
This is fixed by using passing in the preprocessing parameter (true for the examples, false when no /par are to be stripped out) when creating a DocumentCreator
