### ISSUE TITLE
Pre printed stationary

### ISSUE THREAD

**Issue by Parbil** [gmddmg/NTemplates#10]
Hi, this is very good component and I used at many levels. U have case where I need to use it with pre printed stationary. The problem is that some values i need to print on the bottom next it is pre printed label or boxes. How can I achieve this...any guidance highly appreciated

**Comment by gmddmg** [comment]
Hello Parbil, I´m glad you found NTemplates useful. I´m not quite sure I understood your requirement but I will try to help you. For things such as "pre printed" labels you coud try using images. Please take a look at the Letter example, there you can see how to place an image in the document.
Please note that if the labels are just "words" you can generate those images at runtime with .Net.
Also, if you need some kind of background for your document you can try putting an image as the background. I believe that could be easily achieved with an editor such as MS Word.
Hope this helps!

**Comment by seeker25** [comment]
Parbil, Can you provide a screenshot/image for some context?

**Comment by Parbil** [comment]
It is to use with a dot matrix printer with pre printed invoice , it has header and column and on the bottom total fields. regardless of the number of items in the bill the total has to be printed in the total (bottom summary)

**Comment by gmddmg** [comment]
Hi,  that is a typical use case for NTemplates. In my opinion it World be a
tryal and error process till you gel it right. Please check the invoice
example.
Hope this helps.

Cheers,

Gonzalo

**Comment by Parbil** [comment]
Thanks it worked
