### ISSUE TITLE
Single # causes loss of formatting. 

### ISSUE THREAD

**Issue by seeker25** [gmddmg/NTemplates#2]
I tried using a # sign inside of my document. As a part of text. It nuked the entire formatting. 

My advice is to build in some sort of detection to indicate it is simply a single # sign. Either that or switch the symbol to something like handle bars {{{ }}} or ~ which is rarely used. 

I can see running into problems later when people modify the templates with # inside of them and then wonder why the template got all messed up.

**Comment by gmddmg** [comment]
Currently, # is reserved to define placeholders. However those characters can be configured, meaning that you can tell the library what character you want to use for that purpose. Please explore the public properties of the DocumentCreator object. Hope this helps.

**Comment by seeker25** [comment]
Figured it was hard coded in Parser.cs. 

internal static string _d = "#";
