### ISSUE TITLE
Support for Nested If Statements

### ISSUE THREAD

**Issue by seeker25** [gmddmg/NTemplates#5]
Example:

```
~SCAN(S)~
~IF (true)~

BLACK

~IF (true)~

BLACK2

~ENDIF~

HELLO SIR!

~ELSE~

PINK

~ENDIF~
~ENDSCAN~

```

Should result in:

```
BLACK
BLACK2
HELLO SIR!
```

Currently results in:

`BLACK
`

I'm working on fix for this currently.

**Comment by seeker25** [comment]
You may have not intended to use NTemplates this way.

**Comment by gmddmg** [comment]
Yes, you are correct.  The initial idea was for more simple scenarios like the examples that include conditional formatting. Currently Nested IFs are not supported.

**Comment by gmddmg** [comment]
If you are going to work on a fix I would sugest to take a look at how Nested SCANs work, there is at least one example. Also, I would really appreciate in case you get to implement this, if you could provide an example so it's available for other devs. Thx!

**Comment by seeker25** [comment]
I've got it going now. Just have to add the test project and make sure
everything is working.
